### ISSUE TITLE
Jest is unable to close due to SqliteStore open handle

### ISSUE THREAD

**Issue by isaacgr** [theogravity/express-session-sqlite#15]
Not entirely sure whats going on as of yet, but Jest appears to be complaining that its unable to close due to the SqliteStore instance remaining open.

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  Timeout

      31 |     cookie: { maxAge: oneDay },
      32 |     resave: false,
    > 33 |     store: new SqliteStore({
         |            ^
      34 |       driver: sqlite3.Database,
      35 |       path: process.env.DB_PATH,
      36 |       ttl: oneDay,

      at new SqliteStore (node_modules/express-session-sqlite/src/SqliteStore.ts:55:27)
      at Object.<anonymous> (server/server.js:33:12)
      at Object.<anonymous> (tests/server/app.test.js:2:20)
      at async TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:317:13)
      at async runJest (node_modules/@jest/core/build/runJest.js:407:19)
      at async _run10000 (node_modules/@jest/core/build/cli/index.js:338:7)
      at async runCLI (node_modules/@jest/core/build/cli/index.js:190:3)
```
I'm using it the same as shown in the docs:
```
app.use(
  session({
    secret: process.env.SESSION_SECRET,
    saveUninitialized: true,
    cookie: { maxAge: oneDay },
    resave: false,
    store: new SqliteStore({
      driver: sqlite3.Database,
      path: process.env.DB_PATH,
      ttl: oneDay,
      prefix: "sess:",
      cleanupInterval: 300000
    })
  })
);
```
And I dont think its anything in my test.

```
const request = require("supertest");
const { server } = require("../../server/server");
const { ROUTE_PATHS } = require("../../server/utils/constants");
const apiVersion = "/api/v1";

describe(`POST ${ROUTE_PATHS.ACCOUNTS.SIGN_UP}`, () => {
  afterAll((done) => {
    server.close(() => {
      done();
    });
  });
  describe("when passed an email and password", () => {
    test("should respond with a 201 status code", async () => {
      try {
        const response = await request(server)
          .post(`${apiVersion}${ROUTE_PATHS.ACCOUNTS.SIGN_UP}`)
          .send({
            email: "testsuite@gmail.com",
            password: "test"
          });
        expect(response.statusCode).toBe(201);
      } catch (e) {
        throw e;
      }
    });
  });
```

**Comment by isaacgr** [comment]
Ah ok. So I noticed in the tests for this package that the stores cleanupTimer was being cleared after each test. So doing that seemed to fix my issue.

I exported the sessionStore and call `clearInterval` on the`cleanupTimer` and that did the trick.

```
const sessionStore = new SqliteStore({
  driver: sqlite3.Database,
  path: process.env.DB_PATH,
  ttl: oneDay,
  prefix: "sess:",
  cleanupInterval: 300000
});
...
module.exports = { server, sessionStore };
```
Then in my tests:

```
const { server, sessionStore } = require("../../server/server");
...
  afterEach(() => {
    clearInterval(sessionStore.cleanupTimer);
  });
```
Not sure if this is the correct thing to do when testing with this package but it seems to have addressed this issue.
